version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  cloudrun: circleci/gcp-cloud-run@1.0.1
  gcp-cli: circleci/gcp-cli@2.1
executors:

  gcloud-executor:
    docker:
      - image: google/cloud-sdk
  machine-executor:
    machine: true
jobs:
    build:
        docker:
            - image: sugan1234/vaadinrepo:latest
        environment:
          MAVEN_CLI_OPTS: "--batch-mode"
        steps:
            - checkout
            - run: mvn $MAVEN_CLI_OPTS clean package -Pproduction -e
            - store_artifacts:
                path: target
                destination: target
                
    test:
        docker:
            - image: sugan1234/vaadinrepo:latest
        steps:
            - checkout
            - run: mvn test -e
            - store_artifacts:
                path: reports
                destination: reports   
         
    build_push_image_gcr:
            
        description: Build docker image and push to gcr registry
        executor: gcp-gcr/default
        machine:
          image: ubuntu-2004:202010-01
        steps:
          - checkout

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
          requires:
            - build
