version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.1
  gcp-gke: circleci/gcp-gke@0.2.0
executors:

  gcloud-executor:
    docker:
      - image: google/cloud-sdk
  machine-executor:
    machine: true

jobs:
    build:
        docker:
            - image: sugan1234/vaadinrepo:latest
        environment:
          MAVEN_CLI_OPTS: "--batch-mode"
        steps:
            - checkout
            - run: mvn $MAVEN_CLI_OPTS clean package -Pproduction -e
            - store_artifacts:
                path: target
                destination: target
                
    test:
        docker:
            - image: sugan1234/vaadinrepo:latest
        steps:
            - checkout
            - run: mvn test -e
            - store_artifacts:
                path: reports
                destination: reports
                
    build_push_image_gcr:
            
        description: Build docker image and push to gcr registry
        executor: machine-executor
        steps:
          - checkout
          - run:
              name: Build app binary and Docker image
              command: |
                echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
                echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
                echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
                echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
                echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV && source $BASH_ENV
               
          - gcp-gcr/build-image:
              dockerfile: Dockerfile
              google-project-id: GOOGLE_PROJECT_ID
              image: $IMAGE_NAME
              registry-url: "gcr.io"
              tag: §TAG
 
          - gcp-gcr/gcr-auth:
              gcloud-service-key: GOOGLE_CLOUD_KEYS
              google-project-id: GOOGLE_PROJECT_ID
              google-compute-zone: GOOGLE_COMPUTE_ZONE

          - gcp-gcr/push-image:
              google-project-id: GCP_PROJECT_ID
              image: $IMAGE_NAME
              registry-url: "gcr.io"

    gcp_cloudrun_deploy:
        description: Deploy using cloud run
        executor: machine-executor
        steps:
          - cloudrun/init
          - cloudrun/deploy:
              cluster: 'new-cluster'
              cluster-location: europe-west1-b
              platform: 'gke'
              image: 'gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME'
              service-name: 'vaadin-ui-service'
              unauthenticated: true

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - build_push_image_gcr:
          requires:
            - build
    - gcp_cloudrun_deploy:
          requires:
            - build_push_image_gcr
