#YAML file for setting up CI/CD pipeline for Vaadin application in circleci
#The file contains scripts to setup Build and test jobs. Build and test jobs uses the docker image sugan1234/vaadinrepo from dockerhub https://hub.docker.com/repository/docker/sugan1234/vaadinrepo
#Scripts to setup deploy to GCP cloud should be written by build enineers. Kindly use the image ubuntu-2004:202010-01 for setting up deploy to cloud
#ubuntu-2004:202010-01 - recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
#build_push_image_gcr job can be extended further for build,push and deploy to cloud
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  cloudrun: circleci/gcp-cloud-run@1.0.1
  gcp-cli: circleci/gcp-cli@2.1
executors:

  gcloud-executor:
    docker:
      - image: google/cloud-sdk
  machine-executor:
    machine: true
jobs:
    build:
        docker:
            - image: sugan1234/vaadinrepo:latest
        environment:
          MAVEN_CLI_OPTS: "--batch-mode"
        steps:
            - checkout
            - run: mvn $MAVEN_CLI_OPTS clean package -Pproduction -e
            - store_artifacts:
                path: target
                destination: target
                
    test:
        docker:
            - image: sugan1234/vaadinrepo:latest
        steps:
            - checkout
            - run: mvn test -e
          
    build_push_image_gcr:
            
        description: Build docker image and push to gcr registry
        executor: gcp-gcr/default
        machine:
          image: ubuntu-2004:202010-01
        steps:
          - checkout

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
          requires:
            - build
