version: 2.0

jobs:
    build:
        docker:
            - image: sugan1234/vaadinrepo:latest
        environment:
          MAVEN_CLI_OPTS: "--batch-mode"
        steps:
            - checkout
            - run: mvn $MAVEN_CLI_OPTS clean package -Pproduction -e
            - store_artifacts:
                path: target
                destination: target
                
    test:
        docker:
            - image: sugan1234/vaadinrepo:latest
        steps:
            - checkout
            - run: mvn test -e
            - store_artifacts:
                path: reports
                destination: reports
                


    deploy:
       docker:
            - image: google/cloud-sdk
       services:
            - docker:dind
       steps:
           - run:
               name: Prepare env vars
               command: |
                 echo $GCLOUD_SERVICE_KEY > base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
                 echo $GCP_PROJECT_KEY > ./gcloud-service-key.json
                 cat ./gcloud-service-key.json
                 cat ${HOME}/gcloud-service-key.json
                 export $GCP_SERVICE_KEY=cat(${HOME}/gcloud-service-key.json)
                 pwd
          -  gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json    
          -  gcloud --quiet config set project $GCP_PROJECT_ID             
          -  gcloud --quiet builds submit . --config=cloudbuild.yaml                

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - deploy
    - test:
        requires:
          - build
          
          
          
            echo $GCLOUD_SERVICE_KEY > base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            echo $GCP_PROJECT_KEY > ./gcloud-service-key.json
            cat ./gcloud-service-key.json
            cat ${HOME}/gcloud-service-key.json
            export $GCP_SERVICE_KEY=cat(${HOME}/gcloud-service-key.json)