version: 2.0

jobs:
    build:
        docker:
            - image: sugan1234/vaadin_v2:latest
        environment:
          MAVEN_CLI_OPTS: "--batch-mode"
        steps:
            - checkout
            - run: mvn $MAVEN_CLI_OPTS clean package -Pproduction -e
            - store_artifacts:
                path: target
                destination: target
                
    test:
        docker:
            - image: sugan1234/vaadin_v2:latest
        steps:
            - checkout
            - run: mvn test -e
            - store_artifacts:
                path: reports
                destination: reports
                


    deploy:
       docker:
            - image:  google/cloud-sdk
      services:
        - docker:dind
      steps:
        - echo $GCP_SERVICE_KEY > gcloud-service-key.json # Google Cloud service accounts
        - gcloud auth activate-service-account --key-file gcloud-service-key.json
        - gcloud config set project $GCP_PROJECT_ID
        - gcloud builds submit . --config=cloudbuild.yaml                

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
    - deploy