version: 2.0

jobs:
    build:
        docker:
            - image: sugan1234/vaadin_v2:latest
        environment:
          MAVEN_CLI_OPTS: "--batch-mode"
        steps:
            - checkout
            - run: mvn $MAVEN_CLI_OPTS clean package -Pproduction -e
            - store_artifacts:
                path: target
                destination: target
                
    test:
        docker:
            - image: sugan1234/vaadin_v2:latest
        steps:
            - checkout
            - run: mvn test -e
            - store_artifacts:
                path: reports
                destination: reports

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build